---
name: Build and test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install nodeJS
        uses: actions/setup-node@v3
        with: 
            node-version: 18
      - name: Install yarn
        run: yarn install
      - name: Preform linting
        run: yarn lint
