---
name: Build and test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install nodeJS
        uses: actions/setup-node@v3
        with: 
            node-version: 18
      - name: Install yarn
        run: yarn install
      - name: Testing yarn
        run: yarn test
      - name: Preform linting
        run: yarn lint
      - name: Log in DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: "true" 
          tags: 
            ${{ secrets.DOCKERHUB_USERNAME }}/webapp:latest
